# ---------------------------------------------------------------
# HPC Carpentries in the Cloud: Slurm + Software Stack from EESSI
# ---------------------------------------------------------------
#
# The HPC Carpentry Cluster in the Cloud is provided as a public
# service by volunteers. It is provisioned with Magic Castle
# <https://github.com/ComputeCanada/magic_castle> using the EESSI
# <https://eessi.github.io/docs/> software stack. If you need an
# account, please visit <cluster.hpc-carpentry.org>.
#
# Compute responsibly.
#
# Use the HPC_CARPENTRY_CUSTOMIZATION variable to invoke these:
#
# > HPC_CARPENTRY_CUSTOMIZATION=episodes/files/customization/HPCC_MagicCastle_slurm/_config_options.yml
# > export HPC_CARPENTRY_CUSTOMIZATION
---

snippets: "JASMIN"

local:
  prompt: "[you@laptop:~]$"
  shebang: "#!/bin/bash"

remote:
  name: "JASMIN"
  login: "login.jasmin.ac.uk"
  launch: "sci-vm-02.jasmin.ac.uk" # system that we must login to for launching jobs
  portal: "https://accounts.jasmin.ac.uk"
  host: "sci-vm-02"
  hosttype: "x86_64" # architecture family example, output from `uname -m` on a login node
  node: "host1001.jc.rl.ac.uk"
  location: "cluster.hpc-carpentry.org"
  user: "jdoe"
  module_python3: "jaspy"
  login_prompt: "[yourUsername@login-07 ~]$"
  prompt: "[yourUsername@sci-vm-02 ~]$"
  shebang: "#!/bin/bash"

  fs:
    home: "/home/users"

  modules:
    python: "jaspy"


sched:
  name: "Slurm"
  submit:
    name: "sbatch"
    options: "--account=workshop --qos=workshop --partition=debug"
  queue:
    debug: "debug"
    testing: "debug"
    qos: "workshop"
    account: "workshop"
  status: "squeue"
  flag:
    user: "--me"
    interactive: "--account=workshop --qos=inter --partition=interactive"
    histdetail: "--long --jobs"
    name:    "--job-name"
    account: "--account"
    array:   "--array"
    qos:     "--qos"
    time:    "--time"
    queue:   "--partition"
    nodes:   "--nodes"
    tasks:   "--tasks"
    threads: "--cpus-per-task"
  del: "scancel"
  interactive: "srun"
  info: "sinfo"
  comment: "#SBATCH"
  hist: "sacct -u yourUsername"
  hist_filter: ""

episode_order:
  - 10-hpc-intro
  - 11-connecting
  - 12-cluster
  - 13-scheduler
  - 14-environment-variables
  - 15-modules
  - 16-transferring-files
  - 17-parallel
  - 18-resources
  - 19-responsibility
